spring:
  application:
    name: micro-web
    thymelaf:
      cache: false
  redis:
    host: 192.168.17.129
    port: 6379
server:
  port: 8000
  servlet:
    context-path: /ylb

dubbo:
  registry:
    address: zookeeper://localhost:2181
  scan:
    base-packages: com.bjppowernode.microweb
  consumer:
    timeout: 30000
    check: false
    retires: 0

#短信服务myKey:f4ccfaca5a3f31e4f2007902e83e9208，动力节点3680fa919b771148da626bbcbd459475
#
jdwx:
  sms:
    url: https://way.jd.com/chuangxin/dxjk
    content: 【YM】你的验证码是：%s，3分钟内有效！请注意保护信息，不要将该信息转发给其他人！
    appkey: f4ccfaca5a3f31e4f2007902e83e9208
  check:
      url: https://way.jd.com/youhuoBeijing/test
      appkey: f4ccfaca5a3f31e4f2007902e83e9208