spring:
  application:
    name: micro-timedtask

#    dubbo  记录一处错误，zookeeper正常启动，但是项目启动时候会导致正常退出，无法连接，原因尽然是d盘可用空间为0
dubbo:
  registry:
    address: zookeeper://localhost:2181
  scan:
    base-packages: com.bjpowernocd.microtimedtask
  consumer:
    check: false
    timeout: 30000
    retries: 0
kq:

